makerplane/pyEfis

- instruments/ai/__init__.py
- screens/pfd.py
1. Avoid redrawing hidden or uninitialized objects.
2. Get fuel quantity from a proper database key (need to specify tank #)
> Bug fixes:

- config/beagle.cfg
- fix/__init__.py
- instruments/airspeed/__init__.py
- instruments/altimeter/__init__.py
- instruments/hsi/__init__.py
- screens/pfd_sm.py
Created a small screen that could be used on smaller LCD displays.  Also added some configurations to the font size on some instrument widgets.
> Small Screen Definition

- config/main.cfg
- instruments/altimeter/__init__.py
- instruments/tc/__init__.py
- instruments/vsi/__init__.py
- screens/sixpack.py
- Fixed
Repaired the sixpack to keep it from crashing when switching, between combined PFD combo and Sixpack screen. 
VSI marks
Screen layout with Menu.
HSI Color 
- Added
Used sixpack to work out the inclinometer slip / skid indication to the turn coordinator. 
Linked to the YAW in FIX-GW.  Max is +/- 5g's full ball deflection.
10,000 foot indicator to the Altimeter.
> Repair Sixpack and implimented  Slip / Skid

- instruments/tc/__init__.py
- instruments/vsi/__init__.py
- Update Inclinometer to +/-0.15g
- Cleaned up the VSI to make the number easier to read.
- Code Clean up to mostly comply to pep8 not pep257 as mentioned in commit.
> Sixpack update

- hmi/menu.py
- instruments/ai/__init__.py
- pyEfis.py
Make the menu able to disappear and reapppear as necessary.
Small bug fix for the flight director in AI.
Add the ability to link to neighboring PyAvTools and PyAvMap without installation.
> Disappearing menus

- README.rst
- requirements.txt
Again trying to add some install doc and easier with requirements.txt
> doc+requirements

- .gitignore
- Makefile
- README.rst
- pyefis/main.py
- requirements.txt
- setup.py
#42 
This includes:
- A setup.py
- Make targets
- Some minor fixes
> Prepare pyEfis for distribution via PyPI

- pyefis/instruments/NumericalDisplay/__init__.py
- pyefis/instruments/ai/__init__.py
- pyefis/instruments/airspeed/__init__.py
- pyefis/instruments/altimeter/__init__.py
- pyefis/instruments/gauges/abstract.py
- pyefis/instruments/gauges/arc.py
- pyefis/instruments/gauges/egt.py
- pyefis/instruments/gauges/horizontalBar.py
- pyefis/instruments/gauges/numeric.py
- pyefis/instruments/gauges/verticalBar.py
- pyefis/instruments/hsi/__init__.py
- pyefis/instruments/misc/__init__.py
- pyefis/instruments/tc/__init__.py
- pyefis/instruments/vsi/__init__.py
- pyefis/screens/epfd.py
- pyefis/screens/pfd.py
- pyefis/screens/sixpack.py
Was trying to run this on Ubuntu 22.04 and found it did not work.
After replacing many of the implicit conversions to explicit conversions it seems to work OK.
I've not written much code in python so not sure if all the changes I made are the best way to handle this.
But it actually runs on Ubuntu 22.04 with python 3.10 now.
> Updated to run on Python 3.10+ by removing implicit conversions

- pyefis/instruments/ai/__init__.py
> Fix incorrect AI display when fix gateway is restarted

- pyefis/config/main.yaml
- pyefis/gui.py
- pyefis/hmi/__init__.py
- pyefis/hmi/actionclass.py
- pyefis/hmi/buttonmenu.py
- setup.py
Implements the basic features for #115
Requires pycond:
pip install pycond
> Dynamic buttons/menu basic functionality working

- pyefis/instruments/ai/__init__.py
Updated a few methods moving the isVisible() check to ensure data is not lost when updates are sent.
Added showEvents method to redraw the screen when shown to bring it current.
> Ensure AI is not discarding data while it is hidden

- pyefis/config/includes/side-buttons.yaml
- pyefis/config/screenbuilder.yaml
- pyefis/gui.py
- pyefis/main.py
- pyefis/screens/screenbuilder.py
Include config paths in screen builder were not resolved properly, this pull fixes that.
> Fixes some path handling issues

- pyefis/config/main.yaml
- snap/snapcraft.yaml
Change to using strict snap, the embedded android will not work but this will allow us to get the snap published
> Strict snap

- INSTALLING.md
- docs/screenbuilder.md
- extras/extras/pyefis.service
- pyefis/hmi/menu.py
- pyefis/main.py
- snap/snapcraft.yaml
This changes the main.yaml to default.yaml to be consistent with fixgateway and enables daemon in the snap for auto-starting
> Changed default config file, enabled daemon in snap

- pyefis/instruments/button/__init__.py
- pyefis/instruments/listbox/__init__.py
- pyefis/screens/screenbuilder.py
- snap/snapcraft.yaml
This adds ability to navigate some objects on the screen, select and interact with them using a single rotary encoder and button.
Helpful of you do not have a touchscreen or simply prefer physical buttons over the touchscreen. I know from experience using a touchscreen in turbulence if not very fun.
> Screen encoder controller

- docs/screenbuilder.md
- pyefis/config/default.yaml
- pyefis/instruments/gauges/abstract.py
- pyefis/instruments/gauges/verticalBar.py
- snap/snapcraft.yaml
Made gauge colors configurable, updated documentation.
> Add config options

- pyefis/config/weston.ini
- snap/snapcraft.yaml
Thought that I could setup snapcraft.io to build from a different branch, turns out it only supports building from the default branch.
> Snap build

- pyefis/config/default.yaml
- pyefis/gui.py
If the screen size is not defined in the config file, set the screen width/height to match the screen size
> Auto screen size

- docs/screenbuilder.md
- pyefis/config/buttons/screen-android-pfd.yaml
- pyefis/config/buttons/screen-ems-pfd.yaml
- pyefis/config/buttons/screen-ems2-pfd.yaml
- pyefis/config/buttons/screen-radio-pfd.yaml
- pyefis/config/buttons/screen-sixpack-pfd.yaml
- pyefis/config/buttons/units.yaml
- pyefis/config/default.yaml
- pyefis/gui.py
- pyefis/instruments/button/__init__.py
> Button hiding

- docs/screenbuilder.md
- pyefis/config/buttons/auto-pilot-adjust.yaml
- pyefis/config/buttons/auto-pilot-flight-plan.yaml
- pyefis/config/buttons/auto-pilot-heading-hold.yaml
- pyefis/config/default.yaml
- pyefis/instruments/button/__init__.py
Cleanup config files
Resolve issues when dealing with multiple pyefis on same network
Fixed bugs with buttons to allow the auto pilot buttons to work as expected
> Various fixes

- pyefis/config/buttons/auto-pilot-adjust.yaml
- pyefis/config/buttons/auto-pilot-flight-plan.yaml
- pyefis/config/buttons/auto-pilot-heading-hold.yaml
- pyefis/instruments/button/__init__.py
When buttons performed actions those action can trigger signals or callbacks to the same buttons, combine this with re-using the same button config on multiple screens and all sorts of strange interactions will happen.
To address this some actions are not performed when the button is not visible and in other places guards are put in place to block signals to prevent the recursion. Not sure if I found and fixed all of them but so far I've been unable to reproduce any issues.
> Fixed button recusrsion issue

- pyefis/config/screens/android-left-buttons.yaml
- pyefis/config/screens/ems-left-buttons.yaml
- pyefis/config/screens/ems2-left-buttons.yaml
- pyefis/config/screens/pfd-left-buttons.yaml
- pyefis/config/screens/radio-left-buttons.yaml
- pyefis/config/screens/sixpack-left-buttons.yaml
- pyefis/screens/screenbuilder.py
- snap/snapcraft.yaml
Added screen with buttons on the left side and fixed bug in screen builder when options on an instrument config are missing
> More screen examples

- pyefis/config/buttons/auto-pilot-adjust.yaml
- pyefis/config/buttons/auto-pilot-flight-plan.yaml
- pyefis/config/buttons/auto-pilot-heading-hold.yaml
- pyefis/instruments/button/__init__.py
- snap/snapcraft.yaml
Trying to resolve various interactions between multiple pyefis and fix gateways running on multiple nodes
> Dual screen issues

- .coveragerc
to see if that resolves the coverage reports from py-cov-action
> Adding .coveragerc
